name: OpenHouseAdmin
main: org.mctourney.openhouse.OpenHouseAdmin
version: 0.4.0

depend:
  - AutoReferee

softdepend:
  - WorldEdit

commands:
  openhouse:
    aliases: [oh, oha]
    description: Admin commands for Open House tools
    usage: /<command> ...
    permission: openhouse.admin
  coach:
    aliases: [c]
    description: Coach commands for Open House tools
    usage: /<command> ...
    permission: openhouse.coach

permissions:
  openhouse.*:
    default: op
    children:
      openhouse.admin: true
  openhouse.admin:
    default: false
    children:
      openhouse.coach: true
  openhouse.streamer:
    default: false
  openhouse.coach:
    default: false
  openhouse.group.*:
    default: false
